import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className={notoSansKr.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
